import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get('window');

export default StyleSheet.create({
  backgroundImage: {
    flex: 1,
    width: width,
    height: height,
  },
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
  },
  flex: {
    flex: 1,
  },
  safe: { 
    flex: 1, 
    backgroundColor: 'transparent' 
  },
  container: { 
    padding: 20, 
    paddingBottom: 40,
    minHeight: height - 100,
    justifyContent: 'center',
  },
  headerRow: { 
    flexDirection: 'row', 
    alignItems: 'flex-end', 
    gap: 8, 
    marginTop: 24, 
    marginBottom: 32,
    justifyContent: 'center',
  },
  welcome: { 
    color: '#ffffff', 
    fontSize: 28, 
    fontWeight: '700',
    textShadowColor: 'rgba(0, 0, 0, 0.8)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  brand: { 
    color: '#ffffff', 
    fontSize: 32, 
    fontWeight: '900', 
    marginLeft: 8,
    textShadowColor: 'rgba(0, 0, 0, 0.8)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  brandT: { 
    color: '#ff4444',
    textShadowColor: 'rgba(255, 68, 68, 0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  brandH: { 
    color: '#ff6b35',
    textShadowColor: 'rgba(255, 107, 53, 0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  brandR: { 
    color: '#9d4edd',
    textShadowColor: 'rgba(157, 78, 221, 0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  brandY: { 
    color: '#3b82f6',
    textShadowColor: 'rgba(59, 130, 246, 0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  brandL: { 
    color: '#06ffa5',
    textShadowColor: 'rgba(6, 255, 165, 0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  fieldLabel: { 
    color: '#e2e8f0', 
    fontSize: 16, 
    marginTop: 8, 
    marginBottom: 8,
    fontWeight: '600',
    textShadowColor: 'rgba(0, 0, 0, 0.8)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  inputContainer: { 
    borderColor: '#4a5568', 
    backgroundColor: 'rgba(17, 24, 39, 0.9)', 
    height: 60,
    borderRadius: 12,
    borderWidth: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  countryCode: { 
    color: '#e2e8f0', 
    fontSize: 16, 
    marginRight: 12,
    fontWeight: '600',
  },
  helper: { 
    color: '#a0aec0', 
    fontSize: 14, 
    marginTop: 12, 
    marginBottom: 20,
    textAlign: 'center',
    lineHeight: 20,
  },
  continueBtn: { 
    marginTop: 16,
    shadowColor: '#10b981',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  agreeRow: { 
    flexDirection: 'row', 
    alignItems: 'center', 
    marginTop: 24,
    paddingHorizontal: 8,
  },
  checkbox: { 
    width: 22, 
    height: 22, 
    borderRadius: 11, 
    borderWidth: 2, 
    borderColor: '#4a5568', 
    marginRight: 12, 
    backgroundColor: 'transparent',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  checkboxChecked: { 
    backgroundColor: '#10b981', 
    borderColor: '#10b981',
    shadowColor: '#10b981',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
  },
  agreeText: { 
    color: '#cbd5e0', 
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
  },
  link: { 
    color: '#60a5fa',
    fontWeight: '600',
    textDecorationLine: 'underline',
  },
  phoneNumber: { 
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '500',
  },
})