import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#000' },
  segmentContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    paddingVertical: 10,
  },
  segmentBtn: {
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderRadius: 20,
    backgroundColor: '#222',
    marginHorizontal: 6,
  },
  activeSegment: { backgroundColor: '#4E9FFF' },
  segmentText: { color: '#aaa', fontWeight: '600' },
  activeSegmentText: { color: '#fff' },
  card: {
    backgroundColor: '#1E1E1E',
    borderRadius: 12,
    marginVertical: 10,
    marginHorizontal: 12,
    padding: 12,
    shadowColor: '#000',
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 6,
    elevation: 4,
  },
  footerLoader: { paddingVertical: 20 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  emptyText: { color: '#999', fontSize: 15 },
  errorText: { color: '#FF6B6B', fontSize: 15 },
  header: {
    flexDirection: 'row',
    justifyContent: 'flex-end', 
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: '#000',
    position:'absolute',
    right:0,
    top:-10
  },
  profileIconContainer: {
    padding: 5, 
  },
  profileIcon: {
    width: 40, 
    height: 40,
    borderRadius: 20,
    backgroundColor: '#4E9FFF', 
    borderWidth: 2,
    borderColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 5, 
  },
  profileText: {
    color: '#000',
    fontSize: 18,
    fontWeight: 'bold',
  },
})